### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by okbob** [Titor8115/mandown#1]
Hi

your are miss some files

cli/mandown.c:18:10: fatal error: mandown.h: Adresář nebo soubor neexistuje
   18 | #include "mandown.h"
      |          ^~~~~~~~~~~

**Comment by Titor8115** [comment]
> Hi
> 
> your are miss some files
> 
> cli/mandown.c:18:10: fatal error: mandown.h: Adresář nebo soubor neexistuje
> 18 | #include "mandown.h"
> | ^~~~~~~~~~~

It should be good now. I was testing with the header about extern with libxml2 instead of force format and forgot to removing it.

**Comment by okbob** [comment]
čt 16. 4. 2020 v 19:03 odesílatel Titor8115 <notifications@github.com>
napsal:

> Hi
>
> your are miss some files
>
> cli/mandown.c:18:10: fatal error: mandown.h: Adresář nebo soubor neexistuje
> 18 | #include "mandown.h"
> | ^~~~~~~~~~~
>
> It should be good now. I was testing with the header about extern with
> libxml2 instead of force format and forgot to removing it.
>

yes, it is possible to compile it.
