### ISSUE TITLE
Render empty lines

### ISSUE THREAD

**Issue by jloow** [Titor8115/mandown#13]
Empty lines are not printed meaning it is very hard to make out paragraphs.

It would also be good if comments in the markdown file wasn't rendered (but perhaps I should open a new issue for this?).

**Comment by Titor8115** [comment]
I’ll add <br>, and <hr> (or an extra line break  for <p>) to see how it looks when rendered. Initially I though of it as taking too much space. But you are probably right.

About the usage of <!— —>, I really don’t know what should I treat it as...
The project was designed in the hope of people using Markdown as an actual man-page for command line executables to promote the inclusion of good manual page. That being said, every byte should be counted as useful information for the reader....

**Comment by Titor8115** [comment]
@jloow It turns out, you are 100% right about extra newline...
