### ISSUE TITLE
Debian packages for mandown

### ISSUE THREAD

**Issue by barnumbirr** [Titor8115/mandown#14]
Hey,

I've created Debian packages for mandown over at [barnumbirr/mandown-debian](https://github.com/barnumbirr/mandown-debian/releases) and was wondering if you'd be interested in adding them to the installation instructions in the `README`.

If you're up for it, just tell me what you want the formatting to look like and I'll create a PR.

Thanks a lot.
Cheers.

**Comment by alexmyczko** [comment]
Funny, me too: http://phd-sid.ethz.ch/debian/mandown/

**Comment by alexmyczko** [comment]
But will you ITP it or not?

**Comment by barnumbirr** [comment]
I have no intent to ITP at this time, I will however continue to sync the package with upstream.
