### ISSUE TITLE
Builds fine on MacOS with small Makefile addition

### ISSUE THREAD

**Issue by edrozenberg** [Titor8115/mandown#21]
Not a bug but a comment that mdn builds fine on MacOS via the following (assumes use of HomeBrew):

```
brew install libxml2
```
Add libxml2 HomeBrew Cellar include path to the mandown `Makefile` as follows:
```
CFLAGS = -c -g -O3 -Wall -Wsign-compare -Iparser -Iblender -Iinclude -I/usr/include/libxml2 -I/usr/local/Cellar/libxml2/2.9.10_1/include/libxml2 $(DEFINE)
```

**Comment by Titor8115** [comment]
Feedback received!

**Comment by DiegoMagdaleno** [comment]
@edrozenberg Could you try "brew install mandown" pls

**Comment by edrozenberg** [comment]
@Titor8115 that worked fine thanks!

**Comment by DiegoMagdaleno** [comment]
@edrozenberg are you responding to me or to Titor lel

**Comment by edrozenberg** [comment]
Responding to @DiegoMagdaleno actually :)

**Comment by DiegoMagdaleno** [comment]
Thanks, @Titor8115 I think this issue can now be closed :)

**Comment by edrozenberg** [comment]
Great, closing. BTW if mandown ever needs newer libxml2 or ncurses than standard MacOS provides, believe changing the brew formula to `depends_on "ncurses"` and `depends_on "libxml2"` would make it use the homebrew versions of these libs (which would also mean having to install these 2 brews).
