### ISSUE TITLE
keys doesn't work on Fedora 32 Gnome terminal

### ISSUE THREAD

**Issue by okbob** [Titor8115/mandown#23]
page up, page down, space - doesn't work. Vertical resize is ok. Horizontal resize - decrease breaks a  content.

**Comment by Titor8115** [comment]
@okbob Would you mind uploading a screenshot so I could get some ideas about whats happening? I never used Fedora 32 before.

**Comment by Titor8115** [comment]
I see, its the Gnome-terminal vs Xterm thing. Got it

**Comment by ZaWertun** [comment]
Fedora 32, x86_64. I've tested those keys in 4 different terminals (except Gnome terminal, I've got KDE).
Here is results:
+ konsole-20.04.2 - works;
+ xterm-351 - works;
+ kitty-0.18.0 - works;
+ alacritty-0.4.3 - works;

It's definitely something broken within Gnome term.

**Comment by okbob** [comment]
st 1. 7. 2020 v 12:01 odesílatel Yaroslav Sidlovsky <
notifications@github.com> napsal:

> Fedora 32, x86_64. I've tested those keys in 4 different terminals (except
> Gnome terminal, I've got KDE).
> Here is results:
>
>    - konsole-20.04.2 - works;
>    - xterm-351 - works;
>    - kitty-0.18.0 - works;
>    - alacritty-0.4.3 - works;
>
> It's definitely something broken within Gnome term.
>

these keys is working without any problem in pspg there.

Pavel

**Comment by ZaWertun** [comment]
Just installed `gnome-terminal` (version 3.36.1.1) - works here too on my system.

**Comment by ZaWertun** [comment]
mandown-gnome-term-2020-07-01_13.30.02.mkv: https://drive.google.com/file/d/1eo-vlMEGJiPCOVv8nTRyx-rnSityt0wR/view?usp=sharing

**Comment by ZaWertun** [comment]
@okbob How do you install mandown, from sources?

**Comment by okbob** [comment]
st 1. 7. 2020 v 12:53 odesílatel Yaroslav Sidlovsky <
notifications@github.com> napsal:

> @okbob <https://github.com/okbob> How do you install mandown, from
> sources?
>

from sources, I recheck it now, I have fresh master branch

Pavel

**Comment by okbob** [comment]
st 1. 7. 2020 v 12:58 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> st 1. 7. 2020 v 12:53 odesílatel Yaroslav Sidlovsky <
> notifications@github.com> napsal:
>
>> @okbob <https://github.com/okbob> How do you install mandown, from
>> sources?
>>
>
> from sources, I recheck it now, I have fresh master branch
>

and second recheck, and it is my bad.

I executed mandown and not mdn. mdn is working without any problem.

I am sorry for noise

Pavel
