### ISSUE TITLE
Error while compiling on manjaro

### ISSUE THREAD

**Issue by jaredgoodman03** [Titor8115/mandown#27]
I get this error when running `make install`:
```
cc -c -g -O3 -Wall -Wsign-compare -Iparser -Iblender -I/usr/include/libxml2 -D HAS_NCURSESW_H   -c -o src/view.o src/view.c
In file included from src/view.h:9,
                 from src/view.c:1:
src/st_curses.h:4:10: fatal error: ncursesw/ncurses.h: No such file or directory
    4 | #include <ncursesw/ncurses.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/view.o] Error 1
```
I've installed ncurses 6.2 from my package manager, so I'm not sure what I'm doing wrong here. I'm on Manjaro.

**Comment by Titor8115** [comment]
@jaredgoodman03 Sorry I just saw this issue. It appears that Arch-Linux based system have different naming for Ncurses/Ncursesw, and I wasn't prepared for that.

My suggestion is in st_curses.h, changing this

```
#ifdef HAS_NCURSES_H
#include <ncurses.h>
#else
#include <ncursesw/ncurses.h>
#endif
```

to simply

```
#include <ncurses.h>
```

It should be able to compile after the change.
