### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by nereusx** [Titor8115/mandown#28]
You need to fix lines between lines that starting with ``` to not process them.
```shell
# echo hello
```

**Comment by Titor8115** [comment]
Glad you saw my email!
Do you mean not to show ```shell on the pager?
I was thinking that could distinguish different languages, since syntax highlight isn't coming anytime soon.

**Comment by nereusx** [comment]
Στις Sun, 07 Feb 2021 11:28:10 -0800
Titor8115 <notifications@github.com> έγραψε:

> Glad you saw my email!
> Do you mean not to show ```shell on the pager?
> I was thinking that could distinguish different languages, since
> syntax highlight isn't coming anytime soon.
> 


I sent you real example.
This is my source (md2roff) to the man page of my new app.

You notice many "NAME" sections inside the code block (example block).

you have not show the ```...whatever following and display the lines in
between the second ``` without processing.

-- 
Nicholas Christopoulos <mailto:nereus@freemail.gr>
Personal Pages: <https://nicholas-christopoulos.dev>
Github repositories: <https://github.com/nereusx>

**Comment by nereusx** [comment]
https://github.com/nereusx/notes/blob/main/notes.md
![mdn-example](https://user-images.githubusercontent.com/12963781/107161890-510a8c00-69a8-11eb-83cc-a1022a6ecf47.png)
![notes-man-page](https://user-images.githubusercontent.com/12963781/107161893-57006d00-69a8-11eb-9cde-f6609314c4fa.png)

**Comment by Titor8115** [comment]
I found the issue. mdn currently doesn't process blockquote ```. I'll try to address the issue in the new few patchs.
