### ISSUE TITLE
Stdin piping

### ISSUE THREAD

**Issue by tpham3783** [Titor8115/mandown#34]
Hi, I am using ubuntu 20.04, and my terminal is now set to xterm-256color

When I render a mardown document, rather than seeing bullet points, I am seeing "M-BM-7".  Can you tell me what's going on?

Also, is it possible for render from stdin rather than from a file?  

thank you.

-tp

**Comment by Titor8115** [comment]
I believe it has something to do with your Locale setting or Emulator support.
Check if your terminal emulator supports Unicode/widchar (like "•", or emoji). If this is not the problem, checkout some guide to setup your terminal' Locale to support Unicode/widchar.

Right now the program doesn't support direct `stdin`. But I did tweak it to work before (didn't test for very very long `stdin`). 
But I will consider adding that as optional feature. May I ask what kind of purpose do you have in mind directly using `stdin`?

**Comment by tpham3783** [comment]
Thank you.

My terminal is already setup to use utf-8 with an exception of defining global local in the global envvar: LC_ALL.  So this command helped fix the issue:
`
export LC_ALL="$LC_NAME"
`

Alot of my notes are stored in markdown format in the cloud; to view them, I simply pipe them to "python pygments module" directly from stdin of Curl.  Pygments markdown is not bad, but I wish it could be done better; that's why I am experimenting with Mandown.




-tp

**Comment by Titor8115** [comment]
I just pushed a newer version to support basic piping.
Using it should be as simple as `curl yournote.md | mdn`
